### ISSUE TITLE
Unable to Compile project

### ISSUE THREAD

**Issue by hubshi** [lethalskillzz/Android-Fingerprint#1]
Hi!,

I tried to compile the project in android studio 2.3.3 but its unable to sync the Gradle with 
Error:Connection timed out: connect
and unable to resolve the dependencies, can you please address the issue and you may provide an APK in release or kindly provide the pointer to download the APK.

Best Regard,

**Comment by lethalskillzz** [comment]
Hello Attiq,

When you run a project for the first time, Android Studio needs to download
required project dependencies and you are getting Error:Connection timed
out because Android Studio couldn't download these dependencies probably
due to bad internet connection.

Please make sure you are connected to a good internet connection and try
again.

Cheers!

**Comment by mihir815** [comment]
Error:Operation timed out
Same issue, having strong network and tried multiples times..
Still no resolution.

**Comment by gavalle96** [comment]
Hello, 

I would like to use your .so files in my Android Studio project, but I don't know how to use them.

Could you please help me?

Thanks in advance!

**Comment by waqarafz** [comment]
Hi. attiq i resolved this issue by removing these lines from gradle settings 
systemProp.http.proxyPort=8080
systemProp.https.proxyPassword=
systemProp.https.proxyHost=10.71.170.5
systemProp.http.proxyHost=10.71.170.5
systemProp.https.proxyPort=8080
systemProp.https.nonProxyHosts=localhost
systemProp.https.proxyUser=
